### ISSUE TITLE
Auto quit when run rx/wow algorithm

### ISSUE THREAD

**Issue by orangeagain** [skypool-org/xmrig-skypool#1]
问题一：直连矿池跑rx/wow算法自动闪退
问题二：套一个本地xmrig proxy的话就不会断了，但是算法变成了rx/sfx，怎么切换成rx/wow

**Comment by xiaozzz** [comment]
建议加qq群 631930869 联系开发获取更多帮助
1. 如果只想跑rx/wow算法，可以在参数`pass`一栏的结尾，加上`~rx/wow`
2. 由于skypool是机枪池，需要不同算法的算力比例。默认的`xmrig-proxy`只支持`rx/0`以及`rx/sfx`两种算法，要获得全算法支持，需要[skypool-xmrig-proxy](https://github.com/skypool-org/xmrig-proxy)

**Comment by orangeagain** [comment]
代理换成了 skypool-xmrig-proxy，获取到的算法变成 rx/0了，算了不折腾了就这样吧
